### ISSUE TITLE
Hard to find the source

### ISSUE THREAD

**Issue by jlevon** [joyent/smartos-docs#4]
From wiki.smartos.org, it's not particularly easy to find *this* repo. There should be some obvious link, ideally on the main section, to this repo.

**Comment by bahamat** [comment]
I know that it's not the best, but each page has a pencil icon at the top near the right hand side (just to the left of the ToC) that will go to the github page for that file. The way MkDocs works, the repo link in the upper right corner (to the right of the search field in the header bar) can only have one repo, and I wanted that to link to smartos itself. I'm not sure where is best to put a link to the docs source, but I'm open to suggestion.

**Comment by jlevon** [comment]
So I agree that link should go to smartos-live. I don't think the pencil is quite obvious enough.

Personally I would put a brief mention of the wiki source under "Home" page, probably in
the 'How to Use this Site'. In addition, a section under "SmartOS community". I can do that if you think that'd work OK.

**Comment by bahamat** [comment]
Fixed in 05e5007.
