### ISSUE TITLE
Incorrect link to Getting Started with SmartOS

### ISSUE THREAD

**Issue by justforgroups** [joyent/smartos-docs#41]
On page **https://wiki.smartos.org/download-smartos/** the link to 'Getting Started with SmartOS' is **https://wiki.smartos.org/download-smartos/getting-started** which returns a 404 - I think should be **https://wiki.smartos.org/getting-started-with-smartos/**

**Comment by bahamat** [comment]
Thanks! Fixed in a8c0699
